change current_cycler() to current_cycler
Hi Andreas,

I was go this error when running your example in ch 2:
```
     78     current_cycler = mpl.rcParams['axes.prop_cycle']
     79 
---> 80     for i, (yy, cycle) in enumerate(zip(unique_y, current_cycler())):
     81         mask = y == yy
     82         # if c is none, use color cycle

TypeError: 'Cycler' object is not callable
```
the error was fixed when changing `current_cycler()` to `current_cycler` on line 81.

(I'm using Python 3.5)